# preload = /home/xander/Documents/wallpaper/city-skyline.jpg
# wallpaper = ,/home/xander/Documents/wallpaper/city-skyline.jpg
wallpaper {
  monitor =
  path = /home/xander/Documents/wallpaper/city-skyline.jpg
  fit_mode = cover
}
