# Nvidia
LIBVA_DRIVER_NAME=nvidia
__GLX_VENDOR_LIBRARY_NAME=nvidia
NVD_BACKEND=direct
WLR_NO_HARDWARE_CURSORS=1

# Scaling
GDK_SCALE=1.5
XCURSOR_SIZE=32
QT_SCALE_FACTOR=1.5

# Electron (Cursor, etc.) — use native Wayland
ELECTRON_OZONE_PLATFORM_HINT=wayland
